apiVersion: v1
kind: Service
metadata:
  name: armada-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: armada-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: armada-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: armada-api
  template:
    metadata:
      labels:
        app: armada-api
    spec:
      containers:
        - name: armada-api
          image: sublayer/armada-api:$VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: armada-api-config