name: Build Armada API

on:
  release:
    types:
      - created
jobs:
  build-armada-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set tag as environment variable
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the Docker image
        working-directory: ./services/armada-api
        run: docker build . --file Dockerfile_arm64v8 --platform linux/arm64 --output "type=image,push=false" --tag sublayer/armada-api:${{ steps.vars.outputs.tag }}
      - name: Login into Gitlab Docker Registry
        run: docker login -u sublayer -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Gitlab Docker Registry
        run: docker push sublayer/armada-api:${{ steps.vars.outputs.tag }}
